import { Component, signal, input, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Curso } from '../../../../pages/workspace/sub-pages/cursos/infrastructure/interfaces/course';
import { InputTextComponent } from '../../../atoms/input-text/input-text.component';
import { AtomLabel } from '../../../atoms/label/label';
import { AtomLink } from '../../../atoms/link/link';
import List from '../../../atoms/select/list';
import { AtomSelect } from '../../../atoms/select/select';
import { CardCourse } from '../../../molecules/cards/card-course/course-card';

@Component({
      selector: 'template-cursos',
      imports: [
            FormsModule,
            CardCourse,
            AtomSelect,
            InputTextComponent,
            AtomLabel,
            AtomLink,
      ],
      templateUrl: './template-cursos.component.html',
})
export class TemplateCursos {
      // courses
      nameCourseFind = signal('');
      courses = input<Curso[]>([
            {
                  codigo: '803566083',
                  nombre: 'química',
                  numeroSalon: 101,
                  piso: 1,
                  horaInicio: '08:00:00',
                  horaFin: '09:00:00',
                  dia: 'LUNES',
                  profesores: ['Ana Martínez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature1_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566084',
                  nombre: 'aritmética',
                  numeroSalon: 102,
                  piso: 1,
                  horaInicio: '09:10:00',
                  horaFin: '10:10:00',
                  dia: 'LUNES',
                  profesores: ['Luis Hernández', 'Sofía Gómez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature2_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566085',
                  nombre: 'geometría',
                  numeroSalon: 103,
                  piso: 1,
                  horaInicio: '10:40:00',
                  horaFin: '11:40:00',
                  dia: 'LUNES',
                  profesores: ['Juan Pérez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature3_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566086',
                  nombre: 'álgebra',
                  numeroSalon: 201,
                  piso: 2,
                  horaInicio: '11:50:00',
                  horaFin: '12:50:00',
                  dia: 'LUNES',
                  profesores: ['María García'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature4_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566087',
                  nombre: 'razonamiento matemático',
                  numeroSalon: 202,
                  piso: 2,
                  horaInicio: '08:00:00',
                  horaFin: '09:00:00',
                  dia: 'MARTES',
                  profesores: ['Carlos Rodríguez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature5_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566088',
                  nombre: 'razonamiento verbal',
                  numeroSalon: 203,
                  piso: 2,
                  horaInicio: '09:10:00',
                  horaFin: '10:10:00',
                  dia: 'MARTES',
                  profesores: ['Ana Martínez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature6_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566089',
                  nombre: 'literatura',
                  numeroSalon: 204,
                  piso: 2,
                  horaInicio: '10:40:00',
                  horaFin: '11:40:00',
                  dia: 'MARTES',
                  profesores: ['Luis Hernández'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature7_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566090',
                  nombre: 'física',
                  numeroSalon: 301,
                  piso: 3,
                  horaInicio: '11:50:00',
                  horaFin: '12:50:00',
                  dia: 'MARTES',
                  profesores: ['Sofía Gómez', 'Juan Pérez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature8_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566091',
                  nombre: 'historia universal',
                  numeroSalon: 302,
                  piso: 3,
                  horaInicio: '08:00:00',
                  horaFin: '09:00:00',
                  dia: 'MIÉRCOLES',
                  profesores: ['María García'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature9_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566092',
                  nombre: 'cómputo',
                  numeroSalon: 303,
                  piso: 3,
                  horaInicio: '09:10:00',
                  horaFin: '10:10:00',
                  dia: 'MIÉRCOLES',
                  profesores: ['Carlos Rodríguez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature10_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566093',
                  nombre: 'ingles',
                  numeroSalon: 304,
                  piso: 3,
                  horaInicio: '10:40:00',
                  horaFin: '11:40:00',
                  dia: 'MIÉRCOLES',
                  profesores: ['Ana Martínez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature11_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566094',
                  nombre: 'biología',
                  numeroSalon: 305,
                  piso: 3,
                  horaInicio: '11:50:00',
                  horaFin: '12:50:00',
                  dia: 'MIÉRCOLES',
                  profesores: ['Luis Hernández'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature12_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566095',
                  nombre: 'economía',
                  numeroSalon: 101,
                  piso: 1,
                  horaInicio: '08:00:00',
                  horaFin: '09:00:00',
                  dia: 'JUEVES',
                  profesores: ['Sofía Gómez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature13_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566096',
                  nombre: 'educación física',
                  numeroSalon: 102,
                  piso: 1,
                  horaInicio: '09:10:00',
                  horaFin: '10:10:00',
                  dia: 'JUEVES',
                  profesores: ['Juan Pérez', 'María García'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature14_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566097',
                  nombre: 'geografía',
                  numeroSalon: 103,
                  piso: 1,
                  horaInicio: '10:40:00',
                  horaFin: '11:40:00',
                  dia: 'JUEVES',
                  profesores: ['Carlos Rodríguez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature15_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566098',
                  nombre: 'lenguaje',
                  numeroSalon: 201,
                  piso: 2,
                  horaInicio: '11:50:00',
                  horaFin: '12:50:00',
                  dia: 'JUEVES',
                  profesores: ['Ana Martínez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature16_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566099',
                  nombre: 'ortografía',
                  numeroSalon: 202,
                  piso: 2,
                  horaInicio: '08:00:00',
                  horaFin: '09:00:00',
                  dia: 'VIERNES',
                  profesores: ['Luis Hernández'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature17_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566100',
                  nombre: 'cívica',
                  numeroSalon: 203,
                  piso: 2,
                  horaInicio: '09:10:00',
                  horaFin: '10:10:00',
                  dia: 'VIERNES',
                  profesores: ['Sofía Gómez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature18_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566101',
                  nombre: 'historia del perú',
                  numeroSalon: 204,
                  piso: 2,
                  horaInicio: '10:40:00',
                  horaFin: '11:40:00',
                  dia: 'VIERNES',
                  profesores: ['Juan Pérez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature19_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
            {
                  codigo: '803566102',
                  nombre: 'trigonometría',
                  numeroSalon: 301,
                  piso: 3,
                  horaInicio: '11:50:00',
                  horaFin: '12:50:00',
                  dia: 'VIERNES',
                  profesores: ['María García', 'Carlos Rodríguez'],
                  portada: 'https://ultra.content.blackboardcdn.com/ultra/static/images/default-banners/nature20_thumb.jpg',
                  numeroSesiones: 30,
                  contenidos: [],
            },
      ]);
      seasonList = input<List[]>([
            {
                  id: '2024',
                  value: '2024',
            },
            {
                  id: '2025',
                  value: '2025',
            },
      ]);
      studentsList = input<List[]>([
            {
                  id: '00000001',
                  value: 'child-1',
            },
            {
                  id: '00000002',
                  value: 'child-2',
            },
      ]);
      evtChangeCourse = output<string>();

      viewCourses = input<boolean>(true);
}
